detection_dataset:
  class_id: 0
  class_name: mouse
  copy_images: true
  min_box_area: 16
  preview: false
hunyuan:
  #conda_env: hunyuan
  python: /home/try/.conda/envs/hunyuan/bin/python

  model: /home/try/.cache/huggingface/hub/models--tencent--Hunyuan3D-2mv/snapshots/3a761b539b29fe4ff64714813aa9560fd66f5de0
  subfolder: hunyuan3d-dit-v2-mv
  variant: fp16


  num_chunks: 20000
  num_inference_steps: 50
  octree_resolution: 380
  output_type: trimesh
  project_dir: /home/try/code/Hunyuan3D-2
  remove_background: true
  seed: 12345
  subfolder: hunyuan3d-dit-v2-mv
  variant: fp16
  views:
    back: back.jpg
    front: front.jpg
    left: left.jpg
    right: right.jpg
input:
  first_frame: 0
  multi_views_dir: ./tasks/mouse02/views/
  rgbd_dir: ./tasks/mouse02/
output_dir: output/
preset: foundationpose
real_size:
  longest_edge: 0.126
sam2:
  checkpoint: /opt/sam2/checkpoints/sam2.1_hiera_base_plus.pt
  config_file: configs/sam2.1/sam2.1_hiera_b+.yaml
  container: sam2-backend-1
  labels:
  - 1
  points:
  - - 380
    - 182
task: mouse02
