task: mouse008
preset: foundationpose
input:
  rgbd_dir: ./tasks/mouse008/
  multi_views_dir: ./tasks/mouse008/views/
  first_frame: 0
sam2:
  container: sam2-backend-1
  checkpoint: /opt/sam2/checkpoints/sam2.1_hiera_base_plus.pt
  config_file: configs/sam2.1/sam2.1_hiera_b+.yaml
  points:
  - - 374
    - 174
  labels:
  - 1
hunyuan:
  model: tencent/Hunyuan3D-2mv
  subfolder: hunyuan3d-dit-v2-mv
  variant: fp16
  num_inference_steps: 50
  octree_resolution: 380
  num_chunks: 20000
  seed: 12345
  output_type: trimesh
  remove_background: true
  views:
    front: front.jpg
    left: left.jpg
    right: right.jpg
    back: back.jpg
real_size:
  longest_edge: 0.126
detection_dataset:
  class_name: mouse
  class_id: 0
  min_box_area: 16
  copy_images: true
  preview: false
output_dir: output/
